In [119]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [121]:
x = np.linspace(1,1,num=4,dtype=np.int64)
print(x)

[1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])
Y=np.asmatrix(X)
print(Y)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
n = np.linspace(3,10,num=50)
print(n)

[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
p=np.array([[1, 2, 3], [4, 5, 6]])
p.flat[3]
p=p.T
p=np.reshape(p,-1)
print(p)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [122]:
p=np.linspace(1,9,9,dtype=np.int64)
np.split(p,[4,6])

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [123]:
l=np.array([[1,2],[3,4]],dtype=np.int64)
sum=np.trace(l)
l=np.linalg.inv(l)
print(sum)
print(l)

5
[[-2.   1. ]
 [ 1.5 -0.5]]


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [124]:
 xx = np.array([[1,4],[3,1]])
 xl=np.sort(xx,axis=1)
 print(xl)

[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [125]:
yy=np.argsort(xx,axis=1)
print(yy)

[[0 1]
 [1 0]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import random as rnd
arr=np.array([rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9),rnd.randint(1,9)])
arr=arr.reshape(5,2)
max=np.amax(arr,axis=1)
ind=np.argmax(arr,axis=1)
print(arr)
print(max)
print(ind)

[[8 8]
 [6 7]
 [5 4]
 [2 6]
 [3 9]]
[8 7 5 6 9]
[0 1 0 1 1]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [ ]:
print(print(iris_2d[~np.isnan(iris_2d).any(axis=1)]))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Find the correlation between first two columns.

In [ ]:
irish1=iris_2d[:,:1]
irish2=iris_2d[:,1:2]
print(np.corrcoef(irish1,irish2,rowvar=False))

[[ 1.         -0.10936925]
 [-0.10936925  1.        ]]


Find the mean,median and standard deviation of column 3.

In [ ]:
irish3 = iris_2d[:,2]
print(np.average(irish3), np.median(irish3), np.std(irish3))


3.758666666666666 4.35 1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
arr_pl = iris_2d[:,2]
arr_sl = (iris_2d[:,0] ** 2)
arr_vol = (3.14*arr_pl*arr_sl)/3
arr_vol=arr_vol.reshape(150,1)
final=np.concatenate((iris_2d,arr_vol),axis=1)
print(final)

[[5.10000000e+00 3.50000000e+00 1.40000000e+00 2.00000000e-01
  3.81133200e+01]
 [4.90000000e+00 3.00000000e+00 1.40000000e+00 2.00000000e-01
  3.51826533e+01]
 [4.70000000e+00 3.20000000e+00 1.30000000e+00 2.00000000e-01
  3.00571267e+01]
 [4.60000000e+00 3.10000000e+00 1.50000000e+00 2.00000000e-01
  3.32212000e+01]
 [5.00000000e+00 3.60000000e+00 1.40000000e+00 2.00000000e-01
  3.66333333e+01]
 [5.40000000e+00 3.90000000e+00 1.70000000e+00 4.00000000e-01
  5.18853600e+01]
 [4.60000000e+00 3.40000000e+00 1.40000000e+00 3.00000000e-01
  3.10064533e+01]
 [5.00000000e+00 3.40000000e+00 1.50000000e+00 2.00000000e-01
  3.92500000e+01]
 [4.40000000e+00 2.90000000e+00 1.40000000e+00 2.00000000e-01
  2.83688533e+01]
 [4.90000000e+00 3.10000000e+00 1.50000000e+00 1.00000000e-01
  3.76957000e+01]
 [5.40000000e+00 3.70000000e+00 1.50000000e+00 2.00000000e-01
  4.57812000e+01]
 [4.80000000e+00 3.40000000e+00 1.60000000e+00 2.00000000e-01
  3.85843200e+01]
 [4.80000000e+00 3.00000000e+00 1.400000

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [ ]:
arr_species = iris[:,4]
unique, counts = np.unique(arr_species, return_counts=True)
np.size(unique)

3

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
Bin = np.array([])
for i in iris:
  if(float(i[2])<3):
    Bin = np.append(Bin, "small")
  elif(float(i[2])>3 and float(i[2])<5):  
    Bin = np.append(Bin, "medium")
  else:
    Bin = np.append(Bin, "large")
print(Bin)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'large' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'large' 'large' 'large' 'large' 'l

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
arr_petal = iris[:,2].T
#np.size(arr_petal) 150
arr_petal_int = [0]
for i in range(0,150):
  arr_petal_int.append(int.from_bytes(arr_petal[i], "little"))
  i = i+1
arr_petal_int
#np.array(arr_petal,dtype='int64')
rr=np.bincount(arr_petal_int).argmax()
pos=np.where(arr_petal_int==rr)[0][0]
arr_petal[pos]

b'1.4'